steps:
  # Step 0: Terraform Init
  - name: hashicorp/terraform:1.5.0
    id: Terraform Init
    entrypoint: sh
    args:
      - -c
      - |
        terraform init -input=false

  # Step 1: Terraform Format (CHECK ONLY – NO MUTATION)
  - name: hashicorp/terraform:1.5.0
    id: Terraform Format
    entrypoint: sh
    args:
      - -c
      - |
        terraform fmt -check -recursive

  # Step 2: Terraform Validate
  - name: hashicorp/terraform:1.5.0
    id: Terraform Validate
    entrypoint: sh
    args:
      - -c
      - |
        terraform validate

  # Step 3: Terraform Plan
  - name: hashicorp/terraform:1.5.0
    id: Terraform Plan
    entrypoint: sh
    args:
      - -c
      - |
        terraform plan \
          -input=false \
          -var-file="environments/${_ENV}.tfvars" \
          -out=tfplan

  # Step 4: Terraform Apply
  - name: hashicorp/terraform:1.5.0
    id: Terraform Apply
    entrypoint: sh
    args:
      - -c
      - |
        terraform apply -input=false -auto-approve tfplan
        terraform output

substitutions:
  _ENV: dev

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 900s

